### PR TITLE
 Porting the 57th visualization gallery from the NAU rcdata server

### PR DESCRIPTION
**Pull request by nhintruong**
I updated the [57th data viz](https://github.com/tdhock/animint2/blob/4b1049bc1d8ee8dbd78b31f52a5863496fae5931/inst/examples/breakpoints.R) from the NAU rcdata server. This is the rendered version of my fork of the gallery for your preview: https://nhintruong.github.io/gallery/

Here is the solely preview of the new visualization: https://nhintruong.github.io/breakpoints/

@tdhock  @Faye-yufan Could you please review this new gallery update? Thank you

### CODE REVIEW

**Comment by tdhock** [comment]
looks good thanks

**Comment by tdhock** [comment]
where is your master list of all the visualizations which have already been ported / which still need to be ported / etc ?

**Comment by nhintruong** [comment]
> where is your master list of all the visualizations which have already been ported / which still need to be ported / etc ?

Some gallery visualizations won't be ported due to duplication in other data visualizations. The remaining gallery visualizations need to be ported. Should I create an issue titled "List of gallery visualizations that won't be ported due to duplication" or "List of gallery visualizations that still need to be ported"?

**Comment by tdhock** [comment]
yes, another category is "have not yet determined if it has been ported already or not"

**Pull request merged**
