### PR TITLE
Porting visualization gallery

### PR DESCRIPTION
**Pull request by nhintruong**
In this PR, 
- I have ported the 1st, 6th, 7th, 8th, 9th, 10th, 11th, and 13th photos.
- The 3rd photo was already ported, so I omitted it. 
- The 4th and 5th photos are the same, so I skipped the 5th. Photos 14, 15, and 20 are the same as the 13th photo, the 18th photo is the same as the 9th, and the 21st is the same as the 10th. To avoid redundancy, I have not ported these duplicate photos again.

I am currently working on porting the remaining photos from the gallery and will include them in a future pull request.

### CODE REVIEW

**Comment by tdhock** [comment]
please add a comment with links/URLs to your new data viz
please remove any data viz which has already been ported
please include only one data viz at a time in future PRs
please read new guidelines for contribution #6 and suggest improvements/clarifications

**Comment by nhintruong** [comment]
Hi @tdhock @Faye-yufan, as discussed in our recent meeting, I removed data viz that has already been ported. Here is the visualization links of my new data viz for your preview: 

https://nhintruong.github.io/Ch18-neural-networks-sim/
https://nhintruong.github.io/figure-gradient-descent-regression/
https://nhintruong.github.io/figure-aum-convexity-interactive/
https://nhintruong.github.io/figure-curveAlignment/
https://nhintruong.github.io/figure-2019-08-14-animint/
https://nhintruong.github.io/figure-neuroblastomaProcessed-complex/
https://nhintruong.github.io/figure-candidates-interactive

**Comment by tdhock** [comment]
for https://nhintruong.github.io/Ch18-neural-networks-sim/ please remove black border on geom_tile in bottom plot (use color=NA, meaning transparent instead)

**Comment by tdhock** [comment]
https://nhintruong.github.io/figure-gradient-descent-regression/ please remove black border from geom_tile

**Comment by tdhock** [comment]
https://nhintruong.github.io/figure-candidates-interactive/ please remove black border from geom_tile

**Comment by tdhock** [comment]
https://nhintruong.github.io/figure-curveAlignment/ looks good overall but sometimes the grey "Min error" geom_text overlaps with the grey rectangle so can not be read. We could improve by either changing color or moving the text.

**Comment by tdhock** [comment]
https://nhintruong.github.io/figure-2019-08-14-animint/ is ok but the y axis text goes off the screen in the first plot, please try changing y axis text to "Accuracy percent improvement of best GP"

**Comment by tdhock** [comment]
https://nhintruong.github.io/figure-neuroblastomaProcessed-complex/ looks ok but y axis labels and vertical facet labels are sometimes overlapping (text difficult /impossible to read). please fix by adjusting text size / panel spacing / y axis breaks / etc

**Comment by tdhock** [comment]
https://nhintruong.github.io/figure-aum-convexity-interactive/ looks great

**Comment by tdhock** [comment]
thanks!

**Pull request merged**
