### PR TITLE
update contribution instructions

### PR DESCRIPTION
**Pull request by tdhock**
hi @animint/developers
here is a PR with updated README, new instructions are for PR contributors to run `update_gallery()` on their fork, does that make sense? Can you please proof-read and suggest clarifications/improvements?
Here is a link to what the updated gallery will look like if this PR is merged: https://tdhock.github.io/gallery/

### CODE REVIEW

**Comment by ampurr** [comment]
Okay, let's see if I still know how pull requests work... 😖

**Comment by ampurr** [comment]
Made some suggestions, which you're welcome to accept or reject at will. The changes mostly fall in two major categories:

- Changes for reasons related to HTML semantics; e.g. changing "animint2 gallery" to a heading.
- Changes for reasons related to writing clarity; e.g. made the instructions more explicit or obvious.

I haven't really been following `animint2`'s development, so I tried to leave the code snippets and the meaning behind your words unaltered.

**Comment by tdhock** [comment]
hey @ampurr thanks for the review, that is helpful!
Glad to see your comments!
I added you to @animint/developers

**Comment by ampurr** [comment]
Hey, @tdhock! Happy to help. Appreciate your corrections to my comments. :>

**Pull request merged**
